name: build-cn10k-vpp

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  push:
    tags:
      - '[0-9][0-9].[0-9][0-9].0'

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write
env:
  COMPONENT: vpp

jobs:
  ubuntu-cn10k-build:
    name: ubuntu-cn10k-arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Generate cache keys
        id: get_ref_keys
        run: |
          echo 'ccache=ccache-'$(date -u +%Y-%m) >> $GITHUB_OUTPUT
      - name: Retrieve ccache cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.ccache
          key: ${{ steps.get_ref_keys.outputs.ccache }}-${{ github.ref }}
          restore-keys: |
            ${{ steps.get_ref_keys.outputs.ccache }}-refs/heads/main
      - name: Extract version details
        id: version
        run: |
          set -x
          mkdir -p "${PWD}/artifacts"
          git fetch --tags --quiet
          EVENT="${{ github.event_name }}"
          BASE=$(cut -d. -f1,2 < VERSION)
          # If event is a Tag Push
          if [ "$EVENT" = "push" ]; then
            # Start release cycle of minor=0
            # PKG_POSTFIX is empty to signify non-devel
            # Treat HEAD as "release" only if a release tag (YY.MM.0) points at it.
            if git tag --points-at HEAD --list '[0-9][0-9].[0-9][0-9].0' | grep -q .; then
              MINOR=0
              PKG_POSTFIX=""
              IS_DEVEL=false
            else
              #ignore minor for scheduled cron jobs
              MINOR=0
              PKG_POSTFIX="-devel"
              IS_DEVEL=true
            fi
          else
            # Find the latest Tag for this component and base (dao-1.2.*), version-sort, and select the newest.
            LAST=$(git tag -l "${COMPONENT}-${BASE}.*" | sort -V | tail -n1)
            # If no previous tag exists for this base, start at .0; else increment the existing minor.
            if [ -z "$LAST" ]; then MINOR=0 ; else
              MINOR=$(echo "$LAST" | awk -F. '{print $3}')
              MINOR=$((MINOR+1))
            fi
            # -devel specified by the PKG_POSTFIX
            PKG_POSTFIX="-devel"
            IS_DEVEL=true
          fi
          MRVL_PKG_VERSION="${BASE}.${MINOR}"
          echo "MRVL_PKG_VERSION=${MRVL_PKG_VERSION}" >> "${PWD}/artifacts/env"
          echo "PKG_POSTFIX=${PKG_POSTFIX}" >> "${PWD}/artifacts/env"
          DPDK_PKG_VERSION=`cat DPDK_VERSION | grep RELEASE_VERSION | awk -F'=' '{print $2}'`
          DPDK_BASE_PKG_VERSION=`cat DPDK_VERSION | grep BASE_VERSION | awk -F'=' '{print $2}' | awk -F'.' '{print $1"."$2}'`
          echo "DPDK_PKG_VERSION=$DPDK_PKG_VERSION"           >> artifacts/env
          echo "DPDK_BASE_PKG_VERSION=$DPDK_BASE_PKG_VERSION" >> artifacts/env
          echo "DPDK_PKG_VERSION=$DPDK_PKG_VERSION"           >> "$GITHUB_OUTPUT"
          echo "DPDK_BASE_PKG_VERSION=$DPDK_BASE_PKG_VERSION" >> "$GITHUB_OUTPUT"

      - name: push component patch tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          set -x
          source artifacts/env
          NEWTAG="${COMPONENT}-${MRVL_PKG_VERSION}"
          git config user.name "github-bot-accelerator"
          git config user.email "github-bot-accelerator@marvell.com"
          git tag -l "$NEWTAG" | grep -q . || git tag -a "$NEWTAG" -m "devel bump $NEWTAG"
          git push origin "$NEWTAG"

      - name: Build VPP and generate package
        id: build
        run: |
            set -x
            BASE_DIR=${PWD}
            sudo apt-get update -q -y
            sudo apt-get install -y apt-utils gcc meson sudo make dialog ccache git gh build-essential software-properties-common
            git clone "https://github.com/MarvellEmbeddedProcessors/vpp.git"
            cd "${PWD}/vpp"
            PKG_VERSION_NAME=`./src/scripts/version | awk -F '-' '{print $1}'`
            echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}" >> "${BASE_DIR}/artifacts/env"
            CPT_PKG_VERSION=`cat DEP_PKG_VERSION | grep CPT_PKG_VERSION | awk -F'=' '{print $2}'`
            source ${BASE_DIR}/artifacts/env
            DISTRO=ubuntu-`lsb_release -rs`
            echo "DISTRO=${DISTRO}" >> ${BASE_DIR}/artifacts/env
            GH_REPO=MarvellEmbeddedProcessors/dao
            BASE="${MRVL_PKG_VERSION%.*}"
            BEST=$(curl -fsSL "https://api.github.com/repos/${GH_REPO}/releases?per_page=100" | jq -r '.[].tag_name' | grep -E "^oct-ep-target-cn10k-${BASE}\.[0-9]+-${DISTRO}-${TAG}$" | sort -V | tail -n1)
            OCT_PKG_VERSION=$(echo "$BEST" | cut -d- -f5)
            OCT_TAG=${BEST}
            wget -q "https://github.com/MarvellEmbeddedProcessors/dao/releases/download/${OCT_TAG}/oct-ep-target-cn10k${PKG_POSTFIX}_${OCT_PKG_VERSION}_arm64.deb"
            sudo apt-get install -y "./oct-ep-target-cn10k${PKG_POSTFIX}_${OCT_PKG_VERSION}_arm64.deb"
            version_range() {
              local var="$1"
              local full="${!var}"
              local year=$(echo "$full" | cut -d. -f1)
              local month=$(echo "$full" | cut -d. -f2)
              local base="${year}.${month}.0"
              local upper="${year}.$((10#$month + 1)).0"
              export "${var}_BASE"="${base}"
              export "${var}_UPPER"="${upper}"
            }
            version_range MRVL_PKG_VERSION
            mkdir -p "${PWD}/install"
            mkdir -p "${PWD}/install/DEBIAN"
            cd "${PWD}/install"
            echo 'Package: vpp-'$PKG_VERSION_NAME'-cn10k'$PKG_POSTFIX >> DEBIAN/control
            echo 'Version: '$MRVL_PKG_VERSION >> DEBIAN/control
            echo "Maintainer: Jerin Jacob (jerinj@marvell.com)" >> DEBIAN/control
            echo 'Depends: python3, python3-ply, dpdk-'$DPDK_BASE_PKG_VERSION'-cn10k (= '$DPDK_PKG_VERSION'), cpt-firmware-cn10k (= '$CPT_PKG_VERSION'), oct-ep-target-cn10k'$PKG_POSTFIX' (>= '$MRVL_PKG_VERSION_BASE'), oct-ep-target-cn10k'$PKG_POSTFIX' (<< '$MRVL_PKG_VERSION_UPPER')' >> DEBIAN/control
            echo "Architecture: arm64" >> DEBIAN/control
            echo "Homepage: https://wiki.fd.io/view/VPP" >> DEBIAN/control
            echo "Description: Vector Packet Processing (VPP) for Octeon10" >> DEBIAN/control
            cd -
            rm -rf "${PWD}/install/~" "${PWD}/install/home"
            mv "${PWD}/install" "${PWD}/vpp-${PKG_VERSION_NAME}-cn10k${PKG_POSTFIX}_${MRVL_PKG_VERSION}_arm64"
            dpkg --build "vpp-${PKG_VERSION_NAME}-cn10k${PKG_POSTFIX}_${MRVL_PKG_VERSION}_arm64"
            cp "vpp-${PKG_VERSION_NAME}-cn10k${PKG_POSTFIX}_${MRVL_PKG_VERSION}_arm64.deb" ${BASE_DIR}/artifacts/.
      - name: Export version name
        id: artifacts
        run: |
          source "${PWD}/artifacts/env"
          echo $PKG_VERSION_NAME
          echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}" >> "$GITHUB_OUTPUT"
          echo $MRVL_PKG_VERSION
          echo "MRVL_PKG_VERSION=${MRVL_PKG_VERSION}" >> "$GITHUB_OUTPUT"
          echo $DISTRO
          echo "DISTRO=${DISTRO}" >> "$GITHUB_OUTPUT"
          echo $PKG_POSTFIX
          echo "PKG_POSTFIX=${PKG_POSTFIX}" >> "$GITHUB_OUTPUT"
          [[ "$PKG_POSTFIX" == "-devel" ]] && TAG=devel || TAG=${MRVL_PKG_VERSION}
          echo "TAG=${TAG}" >> "$GITHUB_OUTPUT"
          echo "IS_DEVEL=${IS_DEVEL}" >> "$GITHUB_OUTPUT"
      - name: Upload debian package as artifact
        uses: actions/upload-artifact@v4.3.1
        if: ${{ github.event_name == 'push' }}
        with:
          name: vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k${{ steps.artifacts.outputs.PKG_POSTFIX }}_${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}_arm64.deb
          path: ${{ github.workspace }}/artifacts/vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k${{ steps.artifacts.outputs.PKG_POSTFIX }}_${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}_arm64.deb
      - name: Delete existing release
        if: ${{ github.event_name == 'push' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k-${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}-${{ steps.artifacts.outputs.DISTRO }}-${{ steps.artifacts.outputs.TAG }}; then
            gh release delete vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k-${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}-${{ steps.artifacts.outputs.DISTRO }}-${{ steps.artifacts.outputs.TAG }} --cleanup-tag -y
          else
            echo "Release not found"
          fi
        continue-on-error: true
      - name: Release VPP cn10k package
        uses: softprops/action-gh-release@v2.2.2
        if: ${{ github.event_name == 'push' }}
        with:
          draft: false
          tag_name: vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k-${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}-${{ steps.artifacts.outputs.DISTRO }}-${{ steps.artifacts.outputs.TAG }}
          files: |
            ${{ github.workspace }}/artifacts/vpp-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-cn10k${{ steps.artifacts.outputs.PKG_POSTFIX }}_${{ steps.artifacts.outputs.MRVL_PKG_VERSION }}_arm64.deb
