name: build-cn10k-dao

on:
  workflow_dispatch: #manual run after a bug-fix
  inputs:
    component:
      description: dao
      required: true
      default: dao
    
  pull_request:

  schedule:
    - cron: "0 0 * * *" # every day at midnight

  push:
    tags:
      - '[0-9][0-9].[0-9][0-9].0'

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  ubuntu-cn10k-build:
    name: ubuntu-cn10k-arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Extract version details
        id: version
        env:
          COMPONENT: ${{ github.event.inputs.component || 'dao' }}
        run: |
          set -e
          mkdir -p artifacts
          git fetch --tags --quiet

          EVENT="${{ github.event_name }}"

          BASE=$(cut -d. -f1,2 < VERSION)

          if ["$EVENT" = "push"]; then
            MINOR=0
            PKG_POSTFIX=""
            IS_DEVEL=false
          else
            LAST=(git tag -l "${COMPONENT}-${BASE}.*" | sort -V | tail -n1)
            if [ -z "$LAST" ]; then MINOR=0 ; else
              MINOR=$(echo "$LAST" | awk -F. '{print $3}')
              MINOR=$((MINOR+1))
            fi
            PKG_POSTFIX="-devel"
            IS_DEVEL=true
          fi

          PKG_VERSION_NAME="${BASE}.${MINOR}"

          {
            echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}"
            echo "PKG_POSTFIX=${PKG_POSTFIX}"
            echo "IS_DEVEL=${IS_DEVEL}"
          } >> artifacts/env

      - name: push component patch tag
        if: github.event_name == 'workflow_dispatch'
        env:
          COMPONENT: ${{ github.event.inputs.component }}
        run: |
          source artifacts/env
          NEWTAG="${COMPONENT}-${PKG_VERSION_NAME}"
          git config user.name "github-bot-accelerator"
          git config user.email "github-bot-accelerator@marvell.com"
          git tag -l "$NEWTAG" | grep -q . || git tag -1 "$NEWTAG" -m "devel bump $NEWTAG"
          git push origin "$NEWTAG"

      - name: Build packages
        id: build
        run: |
          source artifacts/env
          apt-get update
          apt-get install apt-utils gpg gnupg dpkg-dev curl lsb-release -y
          mkdir -p install
          cd install
          mkdir -p usr/local/tmp/
          touch usr/local/tmp/empty
          mkdir DEBIAN
          echo 'Package: dao'${PKG_POSTFIX} >> DEBIAN/control
          echo 'Version: '${PKG_VERSION_NAME} >> DEBIAN/control
          echo "Maintainer: Jerin Jacob (jerinj@marvell.com)" >> DEBIAN/control
          echo "Architecture: arm64" >> DEBIAN/control     -> matches the build
          echo "Description: Machine learning inference engine for Marvell Octeon 10" >> DEBIAN/control
          cd ..
          mv "${PWD}/install" "${PWD}/dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_arm64"
          dpkg --build "${PWD}/dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_arm64"
          cp -r "${PWD}/dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_arm64.deb" ${BASE_DIR}/artifacts/.

      - name: Export version name
        id: artifacts
        run: |
          source "${PWD}/artifacts/env"
          DISTRO=ubuntu-`lsb_release -rs`
          echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}" >> "$GITHUB_OUTPUT"
          echo "DISTRO=${DISTRO}" >> "$GITHUB_OUTPUT"
          echo "PKG_POSTFIX=${PKG_POSTFIX}" >> "$GITHUB_OUTPUT"
          [[ "$IS_DEVEL" == true ]] && TAG=devel || TAG=${PKG_VERSION_NAME}
          echo "TAG=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Release DAO cn10k package
        uses: softprops/action-gh-release@v2.2.2
        if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
        with:
          draft: false
          tag_name: dao-cn10k-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-${{ steps.artifacts.outputs.DISTRO }}-${{ steps.artifacts.outputs.TAG }}
          files: |
            artifacts/dao${{ steps.artifacts.outputs.PKG_POSTFIX }}_${{ steps.artifacts.outputs.PKG_VERSION_NAME }}_arm64.deb
