name: build-cn10k-dao

on:
  # 1) Manual trigger from the GitHub UI "Run workflow"
  workflow_dispatch:


  # 2) Trigger on pull request events
  pull_request:

  # 3) Scheduled trigger via cron
  schedule:
    - cron: "0 0 * * *" #minute, hour, date of month, month, day of week

  # 4) Trigger on pushes that create/update tags matching
  # Release tags like YY.MM.Minor
  push:
    tags:
      - '[0-9][0-9].[0-9][0-9].0'

# Permission to pushing commits, creating releases, or uploading artifacts
# to publish or install packages, deploy to GitHub Pages
# to authenticate with the GitHub API
permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

env:
  # Set the default component to 'dao'
  COMPONENT: dao

# run on Ubuntu 24.04 ARM
jobs:
  ubuntu-cn10k-build:
    name: ubuntu-cn10k-arm64
    runs-on: ubuntu-24.04-arm

    steps:
      # 1) Checkout the source code from the repository
      - name: Checkout sources
        uses: actions/checkout@v4.2.2
        with:
          # Fetch all history for all branches and tags
          # if you only need the latest commit, set `fetch-depth: 1`.
          fetch-depth: 0

      - name: Extract version details
        id: version
        run: |
          set -x
          mkdir -p artifacts
          git fetch --tags --quiet

          # Capture the current event name ("tag push", "pull_request", "workflow_dispatch", "schedule").
          EVENT="${{ github.event_name }}"

          # Extract first two fields = YY.MM from the VERSION file.
          BASE=$(cut -d. -f1,2 < VERSION)

          # If event is a Tag Push
          if [ "$EVENT" = "push" ]; then
            # Start release cycle of minor=0
            # PKG_POSTFIX is empty to signify non-devel
            MINOR=0
            PKG_POSTFIX=""
            IS_DEVEL=false
          else
            # Find the latest Tag for this component and base (dao-1.2.*), version-sort, and select the newest.
            LAST=$(git tag -l "${COMPONENT}-${BASE}.*" | sort -V | tail -n1)
            # If no previous tag exists for this base, start at .0; else increment the existing minor.
            if [ -z "$LAST" ]; then MINOR=0 ; else
              MINOR=$(echo "$LAST" | awk -F. '{print $3}')
              MINOR=$((MINOR+1))
            fi
            # -devel specified by the PKG_POSTFIX
            PKG_POSTFIX="-devel"
            IS_DEVEL=true
          fi

          # Assemble the full version name as YY.MM.Minor
          PKG_VERSION_NAME="${BASE}.${MINOR}"

          {
            echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}"
            echo "PKG_POSTFIX=${PKG_POSTFIX}"
            echo "IS_DEVEL=${IS_DEVEL}"
            echo "COMPONENT=${COMPONENT}"
          } >> artifacts/env

      - name: push component patch tag
        # Limit this step strictly to manual runs. This prevents tag creation during PRs/schedules/releases.
        if: github.event_name == 'workflow_dispatch'
        run: |
          set -x
          source artifacts/env
          # Build the Tag to be pushed
          NEWTAG="${COMPONENT}-${PKG_VERSION_NAME}"
          # git identity for the tag push
          git config user.name "github-bot-accelerator"
          git config user.email "github-bot-accelerator@marvell.com"
          # If the tag doesn't already exist locally, create it as an annotated tag with a message.
          git tag -l "$NEWTAG" | grep -q . || git tag -a "$NEWTAG" -m "devel bump $NEWTAG"
          # push tag to 'origin'
          git push origin "$NEWTAG"

      - name: Build packages
        id: build
        run: |
          set -x
          source artifacts/env
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install apt-utils gpg gnupg dpkg-dev curl lsb-release -y
          ARCH="$(dpkg --print-architecture)"
          BASE_DIR="${PWD}"
          sudo mkdir -p install
          cd install
          sudo mkdir -p usr/local/tmp/
          sudo touch usr/local/tmp/empty
          sudo mkdir DEBIAN
          echo "Package: dao${PKG_POSTFIX}" >> DEBIAN/control
          echo 'Version: '${PKG_VERSION_NAME} >> DEBIAN/control
          echo "Maintainer: Jerin Jacob (jerinj@marvell.com)" >> DEBIAN/control
          echo "Architecture: ${ARCH}" >> DEBIAN/control     # matches the build
          echo "Description: Machine learning inference engine for Marvell Octeon 10" >> DEBIAN/control
          cd ..
          mv "${PWD}/install" "${PWD}/dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_${ARCH}"
          dpkg --build "dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_${ARCH}"
          cp -r "${PWD}/dao${PKG_POSTFIX}_${PKG_VERSION_NAME}_${ARCH}.deb" ${BASE_DIR}/artifacts/.

      - name: Export version name
        id: artifacts
        run: |
          set -e
          source "${PWD}/artifacts/env"
          DISTRO=ubuntu-`lsb_release -rs`
          echo "PKG_VERSION_NAME=${PKG_VERSION_NAME}" >> "$GITHUB_OUTPUT"
          echo "DISTRO=${DISTRO}" >> "$GITHUB_OUTPUT"
          echo "PKG_POSTFIX=${PKG_POSTFIX}" >> "$GITHUB_OUTPUT"
          [[ "$IS_DEVEL" == true ]] && TAG=devel || TAG=${PKG_VERSION_NAME}
          echo "TAG=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Release DAO cn10k package
        uses: softprops/action-gh-release@v2.2.2
        # Run this step only for : tag-push events (releases) and manual runs (devel).
        if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'workflow_dispatch' }}
        with:
          draft: false
          tag_name: dao-cn10k-${{ steps.artifacts.outputs.PKG_VERSION_NAME }}-${{ steps.artifacts.outputs.DISTRO }}-${{ steps.artifacts.outputs.TAG }}
          files: |
            artifacts/dao${{ steps.artifacts.outputs.PKG_POSTFIX }}_${{ steps.artifacts.outputs.PKG_VERSION_NAME }}_arm64.deb
